#!/usr/bin/env bash
#
# Generate K8s secrets from MISE environment variables
# This script reads secrets from mise environment (including SOPS-encrypted files)
# and generates K8s secret manifests
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

NAMESPACE="lightrag"
OUTPUT_FILE="02-secrets.yaml"
BACKUP_SUFFIX=".backup-$(date +%Y%m%d-%H%M%S)"

log_info() {
  echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
  echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
  echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Base64 encode helper
base64_encode() {
  echo -n "$1" | base64 -w 0 2>/dev/null || echo -n "$1" | base64
}

# Check if running in mise environment
check_mise_env() {
  if [ -z "$MISE_SHELL" ] && [ -z "$MISE_DATA_DIR" ]; then
    log_warning "Not running in mise environment. Some secrets may not be available."
    log_info "Run: mise exec -- $0"
    return 1
  fi
  return 0
}

# Get secret from environment with fallback
get_secret() {
  local var_name="$1"
  local default_value="${2:-}"

  # Try to get from environment
  local value="${!var_name}"

  if [ -z "$value" ]; then
    if [ -n "$default_value" ]; then
      echo "$default_value"
    else
      log_warning "Secret '$var_name' not found in environment"
      echo ""
    fi
  else
    echo "$value"
  fi
}

# Generate secrets YAML
generate_secrets_yaml() {
  log_info "Generating K8s secrets from mise environment..."

  # Get secrets from mise environment
  local redis_password=$(get_secret "REDIS_PASSWORD")
  local llm_api_key=$(get_secret "LLM_BINDING_API_KEY")
  local embedding_api_key=$(get_secret "EMBEDDING_BINDING_API_KEY")
  local openai_api_key=$(get_secret "OPENAI_API_KEY" "$llm_api_key")
  local lightrag_api_key=$(get_secret "LIGHTRAG_API_KEY")
  local lobechat_access_code=$(get_secret "LOBECHAT_ACCESS_CODE")
  local monitor_auth_hash=$(get_secret "MONITOR_BASIC_AUTH_HASH")

  # Validate required secrets
  local missing_secrets=()
  [ -z "$redis_password" ] && missing_secrets+=("REDIS_PASSWORD")
  [ -z "$llm_api_key" ] && missing_secrets+=("LLM_BINDING_API_KEY")
  [ -z "$embedding_api_key" ] && missing_secrets+=("EMBEDDING_BINDING_API_KEY")

  if [ ${#missing_secrets[@]} -gt 0 ]; then
    log_error "Missing required secrets: ${missing_secrets[*]}"
    log_info ""
    log_info "To fix this:"
    log_info "1. Create .env.secrets.json with your secrets (see .env.secrets.example.json)"
    log_info "2. Encrypt with: sops encrypt -i --age \"\$(cat .secrets/mise-age.txt | grep 'public key:' | cut -d: -f2 | xargs)\" .env.secrets.json"
    log_info "3. Run mise environment: mise exec -- $0"
    return 1
  fi

  # Backup existing file
  if [ -f "$OUTPUT_FILE" ]; then
    log_info "Backing up existing secrets to ${OUTPUT_FILE}${BACKUP_SUFFIX}"
    cp "$OUTPUT_FILE" "${OUTPUT_FILE}${BACKUP_SUFFIX}"
  fi

  # Base64 encode secrets
  local redis_password_b64=$(base64_encode "$redis_password")
  local llm_api_key_b64=$(base64_encode "$llm_api_key")
  local embedding_api_key_b64=$(base64_encode "$embedding_api_key")
  local openai_api_key_b64=$(base64_encode "$openai_api_key")
  local lightrag_api_key_b64=$(base64_encode "$lightrag_api_key")
  local lobechat_access_code_b64=$(base64_encode "$lobechat_access_code")
  local monitor_auth_hash_b64=$(base64_encode "$monitor_auth_hash")

  # Generate YAML
  cat >"$OUTPUT_FILE" <<EOF
---
# IMPORTANT: This file is auto-generated by scripts/k8s-generate-secrets.sh from mise environment
# DO NOT edit manually. Update secrets in .env.secrets.json and regenerate.
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

apiVersion: v1
kind: Secret
metadata:
  name: lightrag-secrets
  namespace: $NAMESPACE
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: mise
type: Opaque
data:
  # Redis password (from REDIS_PASSWORD)
  REDIS_PASSWORD: $redis_password_b64

  # OpenAI API Keys (from .env.secrets.json)
  LLM_BINDING_API_KEY: $llm_api_key_b64
  EMBEDDING_BINDING_API_KEY: $embedding_api_key_b64
  OPENAI_API_KEY: $openai_api_key_b64
  LIGHTRAG_API_KEY: $lightrag_api_key_b64

  # LobeChat Access Code (from LOBECHAT_ACCESS_CODE)
  LOBECHAT_ACCESS_CODE: $lobechat_access_code_b64

  # Monitor Basic Auth Hash (from MONITOR_BASIC_AUTH_HASH)
  MONITOR_BASIC_AUTH_HASH: $monitor_auth_hash_b64

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: $NAMESPACE
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: mise
type: Opaque
data:
  # Redis password (must match lightrag-secrets)
  password: $redis_password_b64

EOF

  log_success "Generated $OUTPUT_FILE with secrets from mise environment"
  log_info "Secrets included:"
  echo "  ✓ REDIS_PASSWORD"
  echo "  ✓ LLM_BINDING_API_KEY"
  echo "  ✓ EMBEDDING_BINDING_API_KEY"
  echo "  ✓ OPENAI_API_KEY"
  echo "  ✓ LIGHTRAG_API_KEY"
  echo "  ✓ LOBECHAT_ACCESS_CODE"
  echo "  ✓ MONITOR_BASIC_AUTH_HASH"
}

# Verify generated secrets
verify_secrets() {
  log_info "Verifying generated secrets..."

  if [ ! -f "$OUTPUT_FILE" ]; then
    log_error "Generated file $OUTPUT_FILE not found"
    return 1
  fi

  # Check YAML syntax
  if ! kubectl apply --dry-run=client -f "$OUTPUT_FILE" &>/dev/null; then
    log_error "Generated YAML has syntax errors"
    return 1
  fi

  log_success "Secrets file is valid"

  # Show secret names
  echo ""
  log_info "Secret objects:"
  kubectl apply --dry-run=client -f "$OUTPUT_FILE" -o name 2>/dev/null || true
}

# Main execution
main() {
  echo "======================================"
  echo "  K8s Secrets Generator (MISE-based)"
  echo "======================================"
  echo ""

  # Check mise environment (warning only)
  check_mise_env || true

  # Generate secrets
  if ! generate_secrets_yaml; then
    exit 1
  fi

  # Verify
  if ! verify_secrets; then
    log_error "Verification failed"
    exit 1
  fi

  echo ""
  log_success "Secrets generation complete!"
  echo ""
  log_info "Next steps:"
  echo "  1. Review: cat k8s/$OUTPUT_FILE"
  echo "  2. Deploy: mise run k8s-deploy"
  echo "  3. Or manually: kubectl apply -f k8s/$OUTPUT_FILE"
}

main "$@"
